### ISSUE TITLE
Code Review Morning Session 24 August

### ISSUE THREAD

**Issue by Pyonguk** [ramiaquista/ramiaq-portfolio#11]

**Comment by lfmnovaes** [comment]
I liked the scale animations on the project's images, looks good.
I also have some advice for your project to look even better:
- I think it would look better if you apply `1px` of a white border and use that style on the button in the contact form.
- On this template try to use `.svg` files for the background instead of `.png` files, you will notice that they look better for responsiveness.

**Comment by Pyonguk** [comment]
You are doing great. However, there may be some parts of the code that could be improved. 😃

- It seems to me that the design would look better if we use the same design for all the buttons (e.g. the Toolbar buttons could have the same style as the rest of the page). ✨

- The transitions of some animations could be better if their duration was a little bit longer, that could make them look smoother. 👀

You are doing great, keep it up. 🙌

**Comment by KatIsCoding** [comment]
## Some recommended changes I think are really good changes
----
#### Everything in your project is pretty much finished and it really looks sick! But there are some things that I think will make your code cleaner so the next time you have to change something it won't be that big of a deal!

### Optional Changes:
----
### IDs
```css
  #work1,
  #work3 {
    display: flex;
    flex-direction: row;
    padding: 30px;
  }

  #work2,
  #work4 {
    display: flex;
    flex-direction: row-reverse;
    padding: 30px;
  }
```
- What about instead of using different IDs for every work card, you use different classes? This is because IDs are not needed in this specific case (especially because all the "work cards" are pretty much the same) and the only change that happens is the position of some cards, so what about instead of using multiple IDs you use 2 classes for the "normal" cards and "reverse" cards, I think it will make your code look cleaner and in the future when you add more "works" it is going to be easier for the edition.

### Socials

![image](https://user-images.githubusercontent.com/22417577/130635340-0b389efc-f9f1-45bc-a5a9-6ed77837359c.png)

- That space between the socials looks kinda weird, what about joining them together!! I think it will make it prettier

### Conclusion:
### Good work overall! I really liked this project 
![Cool Gif](https://media.giphy.com/media/1ViLp0GBYhTcA/giphy.gif)

**Comment by ramiaquista** [comment]
Thank's for the advice teammates! 😄
