### ISSUE TITLE
Peer-to-peer code review - 03/09

### ISSUE THREAD

**Issue by mike2611** [ramiaquista/ramiaq-portfolio#17]
# Your work looks great, with very clean code.  :+1: 
## Suggestions
-  For your popup window, you can try to make your buttons look the same size, I think that would make your site look cleaner and homogeneous. :robot:

**Comment by dicodiaz** [comment]
Hello @ramiaquista, awesome job!

I only have a few recommendations:
- Adding a transition to the mobile menu and project popup would give better UX.
- Adding functionality to the technologies drop-down lists of the about me section would also give better UX.
- Creating folders to allocate your CSS and js files instead of allocating them in your root directories would help you keep your files organized.

Apart from that, I find your project to be great and your code to be clean. Keep up the good work!

**Comment by ramiaquista** [comment]
Thank's for the advice teammates! 😄 😄
